module.exports = Object.freeze({
    BLE_NOT_RESPONDING: "BLE_NOT_RESPONDING",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SHARED_ANTENNA_NOT_AVAILABLE: "SHARED_ANTENNA_NOT_AVAILABLE",
    SCAN_ALREADY_ON_GOING: "SCAN_ALREADY_ON_GOING",
    NO_BEACON_DETECTED: "NO_BEACON_DETECTED",
    HARDWARE_INCOMPATIBILITY: "HARDWARE_INCOMPATIBILITY",
    UNKNOWN_BLE_FIRMWARE_VERSION: "UNKNOWN_BLE_FIRMWARE_VERSION"
});