module.exports = Object.freeze({
    POS_ON_DEMAND: "POS_ON_DEMAND",
    SET_MODE: "SET_MODE",
    REQUEST_CONFIG: "REQUEST_CONFIG",
    START_SOS: "START_SOS",
    STOP_SOS: "STOP_SOS",
    REQUEST_TEMPERATURE_STATUS: "REQUEST_TEMPERATURE_STATUS",
    PROXIMITY: "PROXIMITY",
    ANGLE_DETECTION :"ANGLE_DETECTION",
    REQUEST_STATUS: "REQUEST_STATUS",
    SET_PARAM: "SET_PARAM",
    CLEAR_MOTION_PERCENTAGE: "CLEAR_MOTION_PERCENTAGE",
    SMS: "SMS",
    DEBUG_COMMAND: "DEBUG_COMMAND"
});