module.exports = Object.freeze({
    GEOLOC_START: "GEOLOC_START",
    MOTION_START: "MOTION_START",
    MOTION_END: "MOTION_END",
    BLE_CONNECTED: "BLE_CONNECTED",
    BLE_DISCONNECTED: "BLE_DISCONNECTED",
    TEMPERATURE_ALERT: "TEMPERATURE_ALERT",
    BLE_BOND_DELETED: "BLE_BOND_DELETED",
    SOS_MODE_START: "SOS_MODE_START",
    SOS_MODE_END: "SOS_MODE_END",
    ANGLE_DETECTION: "ANGLE_DETECTION",
    GEOFENCING: "GEOFENCING"
});