module.exports = Object.freeze({
    ACTIVITY_COUNTER: "ACTIVITY_COUNTER",
    DEVICE_CONFIGURATION: "DEVICE_CONFIGURATION",
    SHOCK_DETECTION: "SHOCK_DETECTION",
    PERIODIC_ACTIVITY: "PERIODIC_ACTIVITY",
    BLE_MAC: "BLE_MAC"
});