module.exports = Object.freeze({
    STAND_BY: "STAND_BY",
    MOTION_TRACKING: "MOTION_TRACKING",
    PERMANENT_TRACKING: "PERMANENT_TRACKING",
    MOTION_START_END_TRACKING: "MOTION_START_END_TRACKING",
    ACTIVITY_TRACKING: "ACTIVITY_TRACKING",
    OFF: "OFF",
    UNKNOWN: "UNKNOWN"
});