module.exports = Object.freeze({
    DEBUG_CRASH_INFORMATION: "DEBUG_CRASH_INFORMATION",
    TX_POWER_INDEX_VALUE: "TX_POWER_INDEX_VALUE",
    UPLINK_LENGTH_ERR: "UPLINK_LENGTH_ERR",
    GENERIC_ERROR: "GENERIC_ERROR",
    SPECIFIC_FIRMWARE_PARAMETERS: "SPECIFIC_FIRMWARE_PARAMETERS",
    UNKNOWN: "UNKNOWN"
});