module.exports = Object.freeze({
    RESET: "RESET",
    READ_CURRENT_ERROR_AND_SEND_IT: "READ_CURRENT_ERROR_AND_SEND_IT",
    MAKE_TRACKER_RING: "MAKE_TRACKER_RING",
    TRIGGER_AN_ERROR: "TRIGGER_AN_ERROR",
    RESET_BLE_PAIRING: "RESET_BLE_PAIRING",
    TRIGGER_HEARTBEAT_MESSAGE: "TRIGGER_HEARTBEAT_MESSAGE",
    READ_TX_POWER_INDEX: "READ_TX_POWER_INDEX",
    WRITE_TX_POWER_INDEX: "WRITE_TX_POWER_INDEX",
    TRIGGER_BLE_BOOTLOADER: "TRIGGER_BLE_BOOTLOADER",
    SPECIFIC_FIRMWARE_PARAMETERS_REQUEST: "SPECIFIC_FIRMWARE_PARAMETERS_REQUEST",
    CONFIGURE_STARTUP_MODES: "CONFIGURE_STARTUP_MODES",
    START_AND_STOP_BLE_ADVERTISEMENT:"START_AND_STOP_BLE_ADVERTISEMENT"
});