module.exports = Object.freeze({
    SWITCH_ON: "SWITCH_ON",
    SWITCH_OFF: "SWITCH_OFF",
    FLAT_BATTERY: "FLAT_BATTERY",
    ALERT: "ALERT",
    SOS_MODE: "SOS_MODE",
    SOS_MODE_CLEAR: "SOS_MODE_CLEAR",
    RESET: "RESET",
    BLE_ADVERTISING: "BLE_ADVERTISING",
    BLE_BONDED: "BLE_BONDED",
    BLE_DEBONDED: "BLE_DEBONDED",
    BLE_LINK_LOSS: "BLE_LINK_LOSS",
    PROX_WARNING: "PROX_WARNING",
    PROX_WARNING_REMINDER: "PROX_WARNING_REMINDER",
    PROX_ALARM: "PROX_ALARM",
    PROX_ALARM_REMINDER: "PROX_ALARM_REMINDER"
});