module.exports = Object.freeze({
    POSITION_MESSAGE: "POSITION_MESSAGE",
    EXTENDED_POSITION_MESSAGE: "EXTENDED_POSITION_MESSAGE",
    HEARTBEAT: "HEARTBEAT",
    ENERGY_STATUS: "ENERGY_STATUS",
    HEALTH_STATUS: "HEALTH_STATUS",
    SHUTDOWN: "SHUTDOWN",
    FRAME_PENDING: "FRAME_PENDING",
    DEBUG: "DEBUG",
    ACTIVITY_STATUS: "ACTIVITY_STATUS",
    CONFIGURATION: "CONFIGURATION",
    SHOCK_DETECTION: "SHOCK_DETECTION",
    BLE_MAC: "BLE_MAC",
    HEARTBEAT: "HEARTBEAT",
    EVENT: "EVENT",
    DATA_SCAN_COLLECTION: "DATA_SCAN_COLLECTION",
    PROXIMITY_DETECTION: "PROXIMITY_DETECTION",
    SMS: "SMS",
    UNKNOWN: "UNKNOWN"
});

