module.exports = Object.freeze({
    GPS: "GPS",
    GPS_TIMEOUT: "GPS_TIMEOUT",
    ENCRYPTED_WIFI_BSSIDS: "ENCRYPTED_WIFI_BSSIDS",
    WIFI_TIMEOUT: "WIFI_TIMEOUT",
    WIFI_FAILURE: "WIFI_FAILURE",
    XGPS_DATA: "XGPS_DATA",
    XGPS_DATA_WITH_GPS_SW_TIME: "XGPS_DATA_WITH_GPS_SW_TIME",
    BLE_BEACON_SCAN: "BLE_BEACON_SCAN",
    BLE_BEACON_FAILURE: "BLE_BEACON_FAILURE",
    WIFI_BSSIDS_WITH_NO_CYPHER: "WIFI_BSSIDS_WITH_NO_CYPHER",
    BLE_BEACON_SCAN_SHORT_ID: "BLE_BEACON_SCAN_SHORT_ID",
    BLE_BEACON_SCAN_LONG_ID: "BLE_BEACON_SCAN_LONG_ID",
    UNKNOWN: "UNKNOWN"
});