module.exports = Object.freeze({
    USER_ACTION: "USER_ACTION",
    LOW_BATTERY: "LOW_BATTERY",
    DOWNLINK_REQUEST: "DOWNLINK_REQUEST",
    BLE_REQUEST: "BLE_REQUEST",
    BLE_CONNECTED: "BLE_CONNECTED"
});